on:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-and-test:
    name: Run Lint & Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ./nowinandroid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle with caching
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Run lint checks
        run: ./gradlew :app:lintDemoDebug

      - name: Upload lint reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lint-reports
          path: '**/build/reports/lint-results-*.html'

      - name: Run unit tests
        run: ./gradlew :app:testDemoDebugUnitTest
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: '**/build/test-results/testDemoDebugUnitTest/*.xml'

  build-apk:
    name: Build Demo Debug APK
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: lint-and-test

    defaults:
      run:
        working-directory: ./nowinandroid

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: Build Demo Debug APK
        run: ./gradlew :app:assembleDemoDebug

      - name: Upload Demo Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: nowinandroid-demo-debug-apk
          path: '**/build/outputs/apk/**/*.apk'
